---

### This playbook is responsible for installing and configuring Gitlab Runner for our Kubernetes cluster

- hosts: master
  remote_user: root
  connection: ssh
  gather_facts: false     ### Don't need to gather facts because it's not used in script
  vars_files:
          - ./secrets.yaml     ### Encrypted yaml file to store tokens
  tasks:
          - name: Create Runner Namespace
            kubernetes.core.k8s:
                    name: gitlab-runner
                    api_version: v1
                    kind: Namespace
                    state: present
          - name: Deploy Runner ServiceAccount Manifest
            kubernetes.core.k8s:     ### Kubernetes rule from Galaxy
                    state: present     ### Deploy if not present aleardy
                    definition: "{{ lookup('file', './manifests/ServiceAccount.yaml') | from_yaml }}"     ### Get manifest content from manifests/ServiceAccount.yaml
                    apply: true     ### Apply manifest
          - name: Deploy Runner Role Manifest
            kubernetes.core.k8s:
                    state: present
                    definition: "{{ lookup('file', './manifests/Role.yaml') | from_yaml }}"     ### Get manifest content from manifests/Role.yaml
                    apply: true
          - name: Deploy Runner RoleBinding Manifest
            kubernetes.core.k8s:
                    state: present
                    definition: "{{ lookup('file', './manifests/RoleBinding.yaml') | from_yaml }}"     ### Get manifest content from manifests/RoleBinding.yaml
                    apply: true
          - name: Register Runner to the project
            uri:
                    url: "https://git-test.arman-projects.com:8443/api/v4/runners"     ### The gitlab route to request for runners
                    method: POST
                    body_format: form-multipart
                    status_code: [200, 201]
                    body:
                            token: "{{ registration_token }}"     ### Use token defined in vault file
                            description: Kubernetes runner for snapp project
                            tag_list: snapp-project,python
            register: result
          - set_fact:
                  runner_token={{ result.json.token }}
          - name: Get Runner ID
            uri:
                    url: "https://git-test.arman-projects.com:8443/api/v4/runners/all?tag_list=snapp-project,python&type=project_type"     ### Request with query params "tag_list" and "type"
                    method: GET
                    headers:
                            PRIVATE-TOKEN: "{{ access_token }}"     ### Use authentication token provided in vault file
            register: result
          - set_fact:
                  runner_id={{ result.json[0].id }}     ### Get the first element of list "json" which is our runner's specifications.
          - name: Deploy Configmap composed of the gitlab runner's configs
            kubernetes.core.k8s:
                    state: present
                    apply: true
                    definition: "{{ lookup('file', './manifests/Configs.yaml') | from_yaml }}"
          - name: Deploy Runner Deployment Manifest
            kubernetes.core.k8s:
                    state: present
                    definition: "{{ lookup('file', './manifests/Deployment.yaml') | from_yaml }}"
                    apply: true
